name: Cosmwasm Contracts
on:
  pull_request:
  push:


jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [./x/ibc-rate-limit]
        output: [./testdata/rate_limiter.wasm]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install the optimizer
        working-directory: ${{ matrix.workdir }}
        run: >
          rustup target add wasm32-unknown-unknown;
          cargo install cw-optimizoor;

      - name: Build
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo cw-optmizoor

      - name: Test
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo test

      - name: Check Test Data
        working-directory: ${{ matrix.workdir }}
        if: ${{ matrix.output != null }}
        run: >
          ls -R .
#          ls ${{ matrix.output }};
#          ls ./artifacts;
#          diff ${{ matrix.output }} ./artifacts/*.wasm
  

  lints:
    name: Cosmwasm Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [./x/ibc-rate-limit]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          target: wasm32-unknown-unknown

      - name: Format
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo fmt --all -- --check
