name: Cosmwasm Contracts
on:
  pull_request:
  push:


jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [./x/ibc-rate-limit]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Build
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo build --release --all-features;

      - name: Build
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Build
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo fmt --all -- --check

      - name: Build
        working-directory: ${{ matrix.workdir }}
        run: >
          cargo clippy --all-targets -- -D warnings
